name: Build LaTeX document
on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
  pull_request:
    branches: [ main ]
    paths:
      - '**.tex'
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest  # Lighter alternative to texlive-full
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        run: |
          latexmk -pdf resume2.tex
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Rifaath_CV.pdf
          # Make sure this matches the output filename of your LaTeX document
          
      # Optional: Release the PDF when tagging
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: Rifaath_CV.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
