name: Release Compiled PDF 
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume2.tex

      - name: Release
        uses: softprops/action-gh-release@v4
        with:
          tag_name: ${{ env.NOW }}
          files: ./Rifaath_CV.pdf
